name = "SubionosphericVLFInversionAlgorithms"
uuid = "0803ec96-7665-482a-9427-2785addca038"
authors = ["Forrest Gasdia <17058025+fgasdia@users.noreply.github.com>"]
version = "0.0.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
